### PR TITLE
add the ability to add intervals to the timer picker

### PR DESCRIPTION
**Pull request by OmerToledo**

### CODE REVIEW

**Comment by OmerToledo** [comment]
@troberts-28 
i still have 2 issues
take a look at the video :)

1.  it doesnt react the 60
2. when i scroll sometimes there is a weird jumping in the ui
any idea what causing this bugs ?

**Comment by troberts-28** [comment]
Hey @OmerToledo 👋

Thanks for the PR! The issues are related to this: https://github.com/troberts-28/react-native-timer-picker/issues/33.

Essentially, the infinite scroll works by auto-scrolling further up the list when you near the start/end of the list. There is a very slight flicker when it does that and I haven't been able to figure out a way of avoiding that completely. To avoid the flicker being noticeable to the user, the numbers are repeated a given number of times (so it does not have to auto-scroll as often). You'll find props on the `TimerPicker` component to modify the number of repetitions for each picker. The right approach would be to modify those defaults based on the interval (i.e. the length of the list).

Does that make sense?

**Comment by troberts-28** [comment]
Hey @OmerToledo

Sorry, have really slept on this! Will take a look at this this week and get it merged.

**Comment by troberts-28** [comment]
This has now been merged into `v2.0.0`. Thanks @OmerToledo!

Just a minor pointer for future work - use more descriptive commit messages to make it easier for a reviewer to understand your work.

**Pull request closed without merging**
